### ISSUE TITLE
help((

### ISSUE THREAD

**Issue by Slippers23** [Xvirus-Team/Xvirus-Tools#51]
Traceback (most recent call last):
  File "/home/kali/Xvirus-Tools/Xvirus.py", line 1, in <module>
    from util import *
  File "/home/kali/Xvirus-Tools/util/__init__.py", line 5, in <module>                           
    from .tools.dmclear import *                                                                 
  File "/home/kali/Xvirus-Tools/util/tools/dmclear.py", line 3, in <module>                      
    import discord                                                                               
ModuleNotFoundError: No module named 'discord'

**Comment by gumbobr0t** [comment]
`python -m pip install -U discord`

but this is clearly skidded from hazard
