### ISSUE TITLE
Need help again 

### ISSUE THREAD

**Issue by Damonic2** [Xvirus-Team/Xvirus-Tools#56]
python3 Xvirus.py
sh: 1: cls: Permission denied
Traceback (most recent call last):
  File "/root/Xvirus-Tools/Xvirus.py", line 1, in <module>
    from util import *
  File "/root/Xvirus-Tools/util/__init__.py", line 4, in <module>
    from .plugins.utils import *
  File "/root/Xvirus-Tools/util/plugins/utils.py", line 126, in <module>
    config = Config()
             ^^^^^^^^
  File "/root/Xvirus-Tools/util/plugins/utils.py", line 26, in __init__
    self.folder_path = os.path.join(os.getenv('LOCALAPPDATA'), 'xvirus_free')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

This happened and I can't open Xvirus.py

**Comment by Damonic2** [comment]
I am using windows 11
