### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by Darth-Fortis** [Xvirus-Team/Xvirus-Tools#58]
Traceback (most recent call last):
  File "/home/darthfortis/Xvirus-Tools/Xvirus.py", line 4, in <module>
    from util import *
  File "/home/darthfortis/Xvirus-Tools/util/__init__.py", line 4, in <module>
    from .plugins.utils import *
  File "/home/darthfortis/Xvirus-Tools/util/plugins/utils.py", line 8, in <module>
    import tls_client
ModuleNotFoundError: No module named 'tls_client'

**Comment by BombenLegerJan** [comment]
same problem

**Comment by vortexsys** [comment]
how about installing the module lmao

**Comment by Darth-Fortis** [comment]
> how about installing the module lmao

How'd I do that?

**Comment by vortexsys** [comment]
pip install modulename

**Comment by Darth-Fortis** [comment]
new issue:

Traceback (most recent call last):
  File "/home/darthfortis/Xvirus-Tools/Xvirus.py", line 4, in <module>
    from util import *
  File "/home/darthfortis/Xvirus-Tools/util/__init__.py", line 4, in <module>
    from .plugins.utils import *
  File "/home/darthfortis/Xvirus-Tools/util/plugins/utils.py", line 130, in <module>
    config = Config()
             ^^^^^^^^
  File "/home/darthfortis/Xvirus-Tools/util/plugins/utils.py", line 30, in __init__
    self.folder_path = os.path.join(os.getenv('LOCALAPPDATA'), 'xvirus_free')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
